version: '3.9'

services:
  db_mongo:
    build: ./MongoDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - api-cadastra-cliente-kenlo-network

volumes:
  mongodb_data_container:

networks:
  api-cadastra-cliente-kenlo-network:
    driver: bridge


